testing

diff --git a/.appveyor.yml b/.appveyor.yml
--- a/.appveyor.yml
+++ b/.appveyor.yml
@@ -31,14 +31,16 @@ install:
       sudo apt-get update -qq
       sudo apt-get install -y wx-common wine-stable
 
-      curl  -o nsis.exe -L https://prdownloads.sourceforge.net/nsis/nsis-3.05-setup.exe
-      wine nsis-3.04-setup.exe /S
-      if [ ! -f "$HOME/.wine/drive_c/Program Files/NSIS/makensis.exe" ]
+      if [ $ARCH != "armv7" ]
       then
-        echo "NSIS failed to install"
-        exit 1
+        curl -o nsis.exe -L https://prdownloads.sourceforge.net/nsis/nsis-3.05-setup.exe
+        wine nsis.exe /S
+        if [ ! -f "$HOME/.wine/drive_c/Program Files/NSIS/makensis.exe" ]
+        then
+          echo "NSIS failed to install"
+          exit 1
+        fi
       fi
-
       chmod +x build.sh
       
 build_script:
@@ -49,7 +51,7 @@ after_build:
       mv FileZilla.zip filezilla-$ARCH-$APPVEYOR_REPO_TAG_NAME.zip
       Push-AppveyorArtifact "FileZilla" -FileName filezilla-$ARCH-$APPVEYOR_REPO_TAG_NAME.exe
 
-      if ($ARCH -eq "aarch64") {
+      if ($ARCH -ne "armv7") {
         mv FileZilla_3_setup.exe filezilla-$ARCH-$APPVEYOR_REPO_TAG_NAME.exe
         Push-AppveyorArtifact "FileZilla Installer" -FileName filezilla-$ARCH-$APPVEYOR_REPO_TAG_NAME.exe
       }
